routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/Apropos', 'AproposController@index')->name('A-propos');

Route::resource('chiefs', 'ChiefController');

Route::get('/dones', 'ChiefController@dones')->name('dones');


Route::get('/undones', 'ChiefController@undones')->name('undones');

Route::put('change/{id}', 'ChiefController@change')->name('changed');

Route::put('/chiefs/{chief}/affectedTo/{user}', 'ChiefController@affectedTo')->name('chiefs.affectedTo');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>

                    @endif

                    {{ __('You are logged in!') }}
                    <div>
                        <h3 class="bg-aqua">  welcome  : {{ Auth::user()->name }}</h3>
                     </div>
                     <div>
                         <a href="{{ route("chiefs.index") }}">
                             go to Your  Chiefs listes <i class="fa fa-address-book" aria-hidden="false"></i>
                         </a>
                     </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection