routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/Apropos', 'AproposController@index')->name('A-propos');

Route::resource('chiefs', 'ChiefController');

Route::get('/dones', 'ChiefController@dones')->name('dones');


Route::get('/undones', 'ChiefController@undones')->name('undones');

Route::put('change/{id}', 'ChiefController@change')->name('changed');

Route::put('/chiefs/{chief}/affectedTo/{user}', 'ChiefController@affectedTo')->name('chiefs.affectedTo');

app/models/Chief.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Chief extends Model
{
    //
    protected $fillable = [
        'name', 'surename', 'birth', 'descript', 'photo' , 'active'
    ];
}

app/Http/Controllers/ChiefController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Chief;
use App\User;
use Illuminate\Support\Facades\Auth;
use Mockery\Undefined;

class ChiefController extends Controller
{
     /***
     * define users for all users
     * get all users of users model
     */
    public $users;

    public function __construct()
    {
         $this->users = User::getAllUsers();

    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

                if (!Auth::user() ) {

                    notify()->warning("<span class='badge badge-dark'>Are you admin or user !?</span>");
                    return ('<p> Login before or Are you authentified ? </p>');
                } else {

                     //get user connected id
                     $userId = Auth::user()->id;
                    //display all chiefs created by a curente user
                    $chiefs = Chief::where(['creator_id'=>$userId])->orderBy('id','desc')->paginate(3);
                    //$chiefs = Chief::all();
                    //$chiefs = Chief::paginate(3);
                    //get users form Users
                        $users = $this->users;
                    //return ('hello new Chief');
                    //dd($chiefs);
                notify()->info("<span class='badge badge-dark'>welcome to chiefs all list!</span>");
                return view('chiefs.index', compact('chiefs', 'users'));
                }




    }
    /**
     * Display alls chiefs where active egal 1 then dones.
     *
     * @return \Illuminate\Http\Response
     */
    public function dones()
    {
        //get user connected id
        $userId = Auth::user()->id;
        //display all chiefs created by a curente user and active egal done
       $chiefs = Chief::where(['creator_id'=>$userId,'active'=>'1'])->orderBy('id','desc')->paginate(3);
        // $chiefs = Chief::where('active',1)->paginate(3);
           //get users form Users
          $users = $this->users;
          notify()->info("<span class='badge badge-dark'>Done items!</span>");
        return view('chiefs.index',compact('chiefs','users'));

    }

    /**
     * Display alls chiefs where active egal 0 then undones.
     *
     * @return \Illuminate\Http\Response
     */
    public function undones()
    {

          //get user connected id
        $userId = Auth::user()->id;
        //display all chiefs created by a curente user and active egal undone
       $chiefs = Chief::where(['creator_id'=>$userId,'active'=>'0'])->orderBy('id','desc')->paginate(3);
        //$chiefs = Chief::where('active',0)->paginate(3);
          //get users form Users
          $users = $this->users;

          notify()->info("<span class='badge badge-dark'>UnDone items!</span>");
        return view('chiefs.index',compact('chiefs','users'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        //get user connected id
      $userId = Auth::user()->id;

        return view('chiefs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return ('hello new Chief store');

        $chief = new Chief();

        $chief->name = $request->name;
        $chief->surename = $request->surename;
        $chief->birth = $request->birthday;
        $chief->descript = $request->description;
        $chief->photo = $request->photo;
        $chief->active = $request->active;
        $chief->creator_id = $request->creator;
        //dd($chief);
       $chief->save();

       notify()->success("<span class='badge badge-dark'>Chiefs added successfully !</span>");
       return redirect()->route('chiefs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  Chief $chief
     * @return \Illuminate\Http\Response
     */
    public function edit(Chief $chief)
    {
        //
        return view('chiefs.edit', compact('chief'));
    }

    /**
     * changes active values of each chiefs .
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function change(Request $request, $id)
    {
        //change value of active

      // $chief->active = $request->active;
       //$chief->update();
       //return back();

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  Chief $chief
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Chief $chief)
    {
        //  dd($chief);
        //update
        $chief->update($request->all());
        return redirect()->route('chiefs.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     *@param Chief $chief
     * @return \Illuminate\Http\Response
     */
    public function destroy(Chief $chief)
    {
        //delete one chiefs
        $chief->delete();
        return back();
    }


    /**
     * .
     *
     * @param Chief $chief
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function affectedTo(Chief $chief, User $user)
    {
        //
        $chief->affectedTo_id = $user->id;

        $chief->affectedBy_id = Auth::user()->id;

        $chief->update();

        return back();
    }



}

resources/views/chiefs/create.blade.php
@extends('../../layouts/app')
@section('content')
<div class="row">

   <div class="container">
        <p class="container">
        CREATE NEW CHIEF
        </p>
        <div class="alert alert-primary">
            <div class="alert-heading">
                Adding new Chief
            </div>
            <div>
                <a href="{{ route('chiefs.index') }}" class=" btn btn-dark ">Go to List</a>
            </div>

                <form action="{{ route('chiefs.store') }}" method="POST">
                    @csrf
                    <div class="text-center">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" id="name">
                        </div>

                        <div class="form-group">
                            <label for="surename">Surename</label>
                            <input type="text" name="surename" id="name">
                        </div>

                        <div class="form-group">
                            <label for="birthday">Birthday</label>
                            <input type="date" name="birthday" id="birthday">
                        </div>

                        <div class="form-group">
                            <label for="description">Description</label>
                            <input type="text" name="description" id="description">
                        </div>

                        <div class="form-group">
                            <label for="photo">photo</label>
                            <input type="text" name="photo" id="photo">
                        </div>

                        <div class="form-group">
                            <label for="actived">Active:</label>
                            <select class="form-control" id="actived" name="active">
                                <option value="1">Active</option>
                                <option value="0">Unactive</option>
                            </select>
                        </div>
                        <div>
                            <input type="text" name="creator" value="{{ Auth::user()->id }}"  hidden>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                add
                            </button>

                        </div>
                    </div>
                </form>

        </div>

   </div>

</div>


@endsection

resources/views/chiefs/edit.blade.php
@extends('../../layouts/app')
@section('content')
<div class="row">

   <div class="container">
        <p class="container">
        Editing Chiefs
        </p>
        <div class="alert alert-primary">
            <div class="alert-heading">
                Editing chief id <span class="badge badge-danger">{{ $chief->id }}</span>
            </div>
            <div>
                <a href="{{ route('chiefs.index') }}" class=" btn btn-dark ">Go to List</a>
            </div>

                <form action="{{ route('chiefs.update',$chief->id) }}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="text-center">














                        <div class="form-group">
                            <label for="name">Name</label>
                             {{-- name --}}
                             <input type="text" name="name" id="name" value="{{ $chief->name }}" required>
                        </div>

                        <div class="form-group">
                            <label for="surename">Surename</label>
                           {{-- surename --}}
                           <input type="text" name="surename" id="name" value="{{ $chief->surename }}" required>
                        </div>

                        <div class="form-group">
                            <label for="description">Description</label>
                             {{-- descripi --}}
                             <input type="text" name="descript" id="description" value="{{ $chief->descript }}" required>
                        </div>

                        <div class="form-group">
                            <label for="photo">photo</label>
                            {{-- photo --}}
                            <input type="text" name="photo" id="photo" value="{{ $chief->photo }}" required>
                        </div>

                        <div class="form-group">
                            <label for="birthday">Birthday</label>
                            {{-- birthday --}}
                            <input type="date" name="birth" id="birthday" value="{{ $chief->birth }}" required>
                        </div>

                        <div class="form-group">
                            <label for="actived">Active:<span class="badge badge-secondary">   Acctuacliy:{{$chief->active}} </span></label>

                            <select class="form-control" id="actived" name="active" required>
{{--  echo with php native commande to change avtice value  --}}
                                <option value="{{$chief->active}}">
                                    @php
                                    if ($chief->active == '1') {

                                        echo 'Active';
                                    }else {

                                        echo 'Unactive';
                                    }
                                    @endphp
                                </option>
                                {{-- change value of active --}}
                                @php
                                if ($chief->active == '1') {
                                    $chief->active ='0';
                                }else {
                                    $chief->active ='1';
                                }
                                @endphp
                                {{-- set new value --}}
                                <option value="{{ $chief->active }}">
                                @php
                                if ($chief->active == '1') {
                                    echo 'Active';
                                }else {
                                    $chief->active ='1';
                                    echo 'Unative';
                                }
                                @endphp
                                </option>

                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                Update
                            </button>

                        </div>
                    </div>
                </form>

        </div>

   </div>

</div>


@endsection

resources/views/chiefs/index.blade.php
@extends('../../layouts/app')
@section('content')
<div class="row">

   <div class="container">
        <p class="container">
        ALL CHIEFS <i class="fas fa-plus"></i>
        </p>
        <p class="text-center">
            <a href="{{ route('chiefs.create') }}" class="btn btn-lg btn-primary"> <i class="fas fa-plus"></i> Create</a>
            @if (Route::currentRouteName() == 'chiefs.index')
                <a href="{{ route('dones') }}" class="btn btn-lg btn-light">DONES </a>
                <a href="{{ route('undones') }}" class="btn btn-lg btn-success">UNDONES</a>

            @elseif(Route::currentRouteName() == 'dones')
               <a href="{{ route('chiefs.index') }}" class="btn btn-lg btn-primary">ALL </a>
               <a href="{{ route('undones') }}" class="btn btn-lg btn-success">UNDONES</a>

            @elseif(Route::currentRouteName() == 'undones' )
             <a href="{{ route('dones') }}" class="btn btn-lg btn-light">DONES </a>
             <a href="{{ route('chiefs.index') }}" class="btn btn-lg btn-primary">All</a>
            @endif


        </p>
        <p>
            @foreach ($chiefs as $item)
            {{-- DISPLAYING INFORMAIONS ABOUT EACH CHIEFS  --}}
                <div class="alert alert-{{ $item->active == 1 ? 'primary':'secondary' }}">
                    <div class="alert-heading">
                        {{$item->name}} | {{$item->surename}}
                        <span class="badge badge-info">create :{{ $item->created_at }} || update :{{ $item->updated_at }}</span>
                    </div>
                    <div class="row">

                        <p class="col">
                            {{$item->birth}}
                        </p>
                        <p class="col">
                            {{$item->descript}}
                        </p>
                        <p class="col">
                            {{$item->photo}}
                        </p>
                        <p class="col">
                     {{-- DISPLAYING INFORMAIONS ABOUT EACH CHIEFS  --}}
                            {{-- button affect user  --}}
                              <form action="#" method="POST">
                                  @method('PUT')
                                    <div class="dropdown mx-2">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        affected :
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            {{-- fetch all users in dropdown elements --}}
                                            @foreach ($users as $user)
                                            <a class="dropdown-item" href="#">{{ $user->name}}</a>
                                            @endforeach

                                        </div>
                                    </div>
                             </form>


                            {{-- button active on unactive --}}

                            <form action="{{ route('chiefs.update',$item->id) }}" method="POST">
                                @method('PUT')
                                @csrf

                                 {{-- name --}}
                                 <input type="text" name="name" id="name" value="{{ $item->name }}" required hidden>
                                 {{-- surename --}}
                                 <input type="text" name="surename" id="name" value="{{ $item->surename }}" required hidden>
                                 {{-- descripi --}}
                                 <input type="text" name="description" id="description" value="{{ $item->descript }}" required hidden>
                                 {{-- photo --}}
                                 <input type="text" name="photo" id="photo" value="{{ $item->photo }}" required hidden>
                                 {{-- birthday --}}
                                 <input type="date" name="birthday" id="birthday" value="{{ $item->birth }}" required hidden>

                                <input type="number" value="{{ $item->active == 1 ? '0':'1'  }}" name="active" required hidden>
                                <button class="btn btn-sm btn-{{ $item->active == 1 ? 'success':'warning' }}">
                                    @if ($item->active == 1)
                                    {{ "done" }}
                                    @else
                                    {{ "undone" }}
                                    @endif
                                </button>
                            </form>
                         {{-- button active on unactive --}}

                        </p>

                        {{-- button eDIT --}}
                        <p class="col">
                            {{-- button edit --}}
                            <a href="{{ route('chiefs.edit',$item->id) }}" class="btn btn-sm btn-warning mx-1">EDIT</a>

                            {{-- button delete --}}
                           <form action="{{ route('chiefs.destroy',$item->id) }}" method="POST">
                               @method('DELETE')
                                @csrf
                            <button class="btn btn-sm btn-danger">DELETE</button>
                           </form>

                        </p>
                    </div>

                </div>
            @endforeach
            {{$chiefs->links()}}
        </p>

   </div>

</div>


@endsection